# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 5 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: redcarpet
disqus: cachapline8
comments: true

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Christopher Chapline

description: My adventures in development
author:
  name: Christopher Chapline
  email: cachapline8@gmail.com
  github: gizmo385
  bio: Computer Science student at the University of Arizona

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
